### ISSUE TITLE
add another method to specify github token

### ISSUE THREAD

**Issue by nktks** [suzuki-shunsuke/tfcmt#1090]
### Feature Overview

We would like to add another method to specify github token to tfcmt.

Currently, it seems tfcmt uses github token only from `GITHUB_TOKEN` environment variable.
https://github.com/suzuki-shunsuke/tfcmt/blob/main/pkg/notifier/github/client.go#L74-L84
https://github.com/suzuki-shunsuke/tfcmt/blob/main/pkg/controller/controller.go#L153
https://github.com/suzuki-shunsuke/tfcmt/blob/main/pkg/config/config.go#L22
Since `GitHubToken` is ignored from yaml config, it always gets from `GITHUB_TOKEN` environment variable.

### Why is the feature needed?

We uses GitHub Provider and it seems it always uses `GITHUB_TOKEN` environment variable to authenticate if env variable exists.
https://registry.terraform.io/providers/integrations/github/latest/docs#oauth--personal-access-token

Even if we specify provider using another GitHub App like below, it prioritizes to use env variable and got below error.
provider:
```
provider "github" {
  app_auth {
    id              = $id
    installation_id = $instration_id
    pem_file        = $pen_file
  }

  owner = "owner"
}
```

error:
```
│ Error: "app_auth": conflicts with token
│ 
│   with provider["registry.terraform.io/integrations/github"],
│   on providers.tf line 6, in provider "github":
│    6: provider "github" {
``` 

### Example Code

same as `Why is the feature needed?`

**Comment by suzuki-shunsuke** [comment]
Thank you for your proposal.
It makes sense.

How about supporting the environment variable `TFCMT_GITHUB_TOKEN`?

**Comment by nktks** [comment]
Thanks for your response!

> How about supporting the environment variable TFCMT_GITHUB_TOKEN?

Sounds great!

**Comment by suzuki-shunsuke** [comment]
- https://github.com/suzuki-shunsuke/tfcmt/pull/1091

**Comment by suzuki-shunsuke** [comment]
@nktks

Published a prerelease version v4.8.0-1. https://github.com/suzuki-shunsuke/tfcmt/releases/tag/v4.8.0-1
Could you try this release?
If there is no problem, we'll release v4.8.0.

**Comment by nktks** [comment]
Thank you!
I'll confirm v4.8.0-1.

**Comment by nktks** [comment]
I confirmed in our private repo and it worked!

**Comment by suzuki-shunsuke** [comment]
Thank you!
v4.8.0 is out 🎉
https://github.com/suzuki-shunsuke/tfcmt/releases/tag/v4.8.0
