### ISSUE TITLE
Detect Omit long plan automatically

### ISSUE THREAD

**Issue by petr-stupka** [suzuki-shunsuke/tfcmt#1363]
### Feature Overview

Hi, this is working very well - #227

```hcl
aws_elb.foo_a: Modifying... [id=foo-a-production]
aws_elb.foo_a: Modifications complete after 2s [id=foo-a-production]

# ...
# ... The maximum length of GitHub Comment is 65536, so the content is omitted by tfcmt.
# ...

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

However i would like to be able to detect the plan has been omitted and i would like add warning into the template. Something like "Plan is ommited" in this style

<img width="345" alt="image" src="https://github.com/user-attachments/assets/5d3def5d-a217-4560-b212-90399388bf35">

Thank you

### Why is the feature needed?

To avoid confusion i.e. when using text search for specific change (why it is not in the plan)

**Comment by suzuki-shunsuke** [comment]
Thank you for your feedback!
It makes sense.

I'm working on this.

- https://github.com/suzuki-shunsuke/tfcmt/pull/1365

**Comment by suzuki-shunsuke** [comment]
How about this?

<img width="929" alt="image" src="https://github.com/user-attachments/assets/005a9234-333b-471d-8152-4944320e4107">

--

<img width="1001" alt="image" src="https://github.com/user-attachments/assets/88cd00f3-1307-44b8-b0b2-3455919652e7">

**Comment by petr-stupka** [comment]
I love that! Thank you

**Comment by suzuki-shunsuke** [comment]
Thank you for your confirmation!

tfcmt v4.13.0 is out 🎉
https://github.com/suzuki-shunsuke/tfcmt/releases/tag/v4.13.0
