### ISSUE TITLE
Send SIGTERM to terraform

### ISSUE THREAD

**Issue by maruloop** [suzuki-shunsuke/tfcmt#1413]
### Feature Overview

Sending SIGTERM like tini if a job on GitHub Action is canceled.
https://github.com/orgs/community/discussions/26311#discussioncomment-8858853

### Why is the feature needed?

When I run terraform on GitHub Actions and I cancel a job during terraform apply, terraform can't release a state lock because it seems GitHub Actions runner doesn't send SIGINIT or SIGTERM to the terraform process.
https://github.com/orgs/community/discussions/26311

There seems to be some workarounds on the above discussion. I though if tfcmt supports like tini, it might be useful.

**Comment by suzuki-shunsuke** [comment]
https://github.com/suzuki-shunsuke/tfcmt/blob/29c0119c85668de99a5272f2185d9ec62dffe032/cmd/tfcmt/main.go#L23
https://github.com/suzuki-shunsuke/tfcmt/blob/29c0119c85668de99a5272f2185d9ec62dffe032/pkg/controller/plan.go#L63-L70

tfcmt sends SIGINT.

**Comment by suzuki-shunsuke** [comment]
I remembered the related discussion. https://github.com/suzuki-shunsuke/tfaction/discussions/1504

**Comment by maruloop** [comment]
Thank you for you reploy. I missed the `setCancel`.
My issue seems not to be related to tfcmt... I will check it in depth on my side!
