### ISSUE TITLE
When using plan output file as source, -patch option seems to create a new comment every time

### ISSUE THREAD

**Issue by jamengual** [suzuki-shunsuke/tfcmt#1454]
### tfcmt version

```console
4.14.0
```

### Environment

* OS: linux
* CPU Architecture: amd64

### Overview

when using this strategy : 
```bash
#!/usr/bin/env bash

set -u

tfcmt plan -- terraform plan 2>&1 | tee result.txt
code=${PIPESTATUS[0]}
tfcmt --output plan.md plan -patch -- bash -c "cat result.txt && exit "$code""
```

tfcmt seems to post new comments every time. This does not happen when running plan directly without `--output` as a parameter using the same version.

### How to reproduce

in the description

### Debug output

```console
$ 
```

### Expected behaviour

to update the last comments

### Actual behaviour

it creates a comment every time

### Important Factoids

related to : (https://github.com/suzuki-shunsuke/tfcmt/issues/1412)

**Comment by jamengual** [comment]
https://github.com/suzuki-shunsuke/tfcmt/issues/1412

**Comment by suzuki-shunsuke** [comment]
You should use `-patch` in the first command because it posts a comment to GitHub.
The second command outputs to `plan.md` so `-patch` option has no meaning.

```sh
#!/usr/bin/env bash

set -u

tfcmt plan -patch -- terraform plan 2>&1 | tee result.txt
code=${PIPESTATUS[0]}
tfcmt --output plan.md plan -- bash -c "cat result.txt && exit "$code""
```

**Comment by jamengual** [comment]
ah, yes, you are correct; I will try that.

**Comment by suzuki-shunsuke** [comment]
I close this issue.

- https://github.com/suzuki-shunsuke/tfcmt/issues/1454#issuecomment-2452696784

**Comment by jamengual** [comment]
I can confirm that it worked, thanks.
