### ISSUE TITLE
Write to a local md file instead of git

### ISSUE THREAD

**Issue by isaaguilar** [suzuki-shunsuke/tfcmt#194]
It would be nice if the tool can have an option to fill in the `plan` or `apply` template to a local file instead of forcing this script to post directly to a PR.  I would guess it could be an option of the commands, like: 

```bash
tfcmt plan -output /my/local/plan.md -- terraform plan
```

**Comment by suzuki-shunsuke** [comment]
Could you explain why this feature is needed?
For debugging?

**Comment by isaaguilar** [comment]
Debugging is one reason. I did actually strip out the "pr commenter" to test this first.

But another reason, the one I'm solving in my particular case, is the script that executes my terraform doesn't have knowledge of the PR that triggered the execution. By saving a file, i'd be able to send it or read it later when another script might know where to comment.

**Comment by robinsk** [comment]
Now that GitHub has launched [job summaries](https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/), it would be nice to post the markdown as [`$GITHUB_STEP_SUMMARY` content](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-job-summary).

**Comment by suzuki-shunsuke** [comment]
- https://github.com/suzuki-shunsuke/tfcmt/pull/654

**Comment by suzuki-shunsuke** [comment]
#654 was merged and I published a prerelease version [v4.2.0-1](https://github.com/suzuki-shunsuke/tfcmt/releases/tag/v4.2.0-1).

Document: https://suzuki-shunsuke.github.io/tfcmt/output-file

Please try [v4.2.0-1](https://github.com/suzuki-shunsuke/tfcmt/releases/tag/v4.2.0-1) and give me your feedback.
If there is no problem, I'll release v4.2.0.

**Comment by NikitaCOEUR** [comment]
It's fine for me. No problem to use it via my CI.

Just, I use it to publish MD content to GITHUB_STEP_SUMMARY, and the "CI LINK" is not necessary for me but it's ok.

**Comment by NikitaCOEUR** [comment]
I think that using the configuration file to specify not to use the "CI Link" is sufficient, as the existing configuration allows for it. Additionally, in my opinion, it is not necessary to introduce the feature that would support the type of notifier.

**Comment by NikitaCOEUR** [comment]
Finally, having the type of Notifier available in the config file could be a plus... We could use the same config file for both Github comment and markdown file.

**Comment by suzuki-shunsuke** [comment]
Released. https://github.com/suzuki-shunsuke/tfcmt/releases/tag/v4.2.0

@NikitaCOEUR Thank you for your contribution!
