### ISSUE TITLE
Creating a label fails when label length is too long

### ISSUE THREAD

**Issue by itkq** [suzuki-shunsuke/tfcmt#252]
We have a terraform monorepo and are using tfcmt for terraform plan CI. Creating label sometimes fails due to such deep hierarchies like:

![tfcmt-failure](https://user-images.githubusercontent.com/8341422/163533746-23d54fd6-d53e-433a-9aad-31e7b1ab0e74.png)

The plan output is available, but we're in trouble when there's many changes like updating dependencies across tfstates because it will be hard to judge if there's a change by the labels. I couldn't find the official document that describes the quota, but I found out the maximum characters is 50 from the Web UI. 

![image](https://user-images.githubusercontent.com/8341422/163534716-dbce17ad-4c7e-45fa-8c00-125f60593419.png)

Here's a basic approach to the problem: Omit the head of the label when it's too long. I'd like to submit a PR in this way, but I'm wondering if this behavior should be optional.

**Comment by suzuki-shunsuke** [comment]
Thank you for your report.
As you said, this is a limitation of GitHub.

> Here's a basic approach to the problem: Omit the head of the label when it's too long.
> I'd like to submit a PR in this way, but I'm wondering if this behavior should be optional.

I think tfcmt shouldn't omit the pull request label, because the label for the other service may be set wrongly.

User should shorten the target value.

**Comment by suzuki-shunsuke** [comment]
The pull request label should be unique and human readable.
So tfcmt shouldn't omit the pull request label mechanically.

**Comment by itkq** [comment]
On the second thought, shortening the label by tfcmt caller is enough for our case. Thanks for the comment! Closing
