### ISSUE TITLE
Support for Github Enterprise

### ISSUE THREAD

**Issue by mechastorm** [suzuki-shunsuke/tfcmt#300]
Would it be possible for this tool to post a comment on a Github Enterprise installation instead? From the looks of this, it seems to be only for Github.com and I do not see any option to specify the GITHUB_URL.

Similar to this mercari/tfnotify issue https://github.com/mercari/tfnotify/pull/91

**Comment by suzuki-shunsuke** [comment]
Thank you for your feedback.
Could you try to set `ghe_base_url` in tfcmt.yaml?

e.g. tfcmt.yaml

```yaml
ghe_base_url: https://example.com
```

I haven't used GitHub Enterprise, so I can't confirm if it works well.

**Comment by mechastorm** [comment]
Thank you very much! I can confirm that this works in GHE with the suggested config

For other references, my tfcmt.yaml config is just like so

```
ghe_base_url: https://github.sec.samsung.net
```

And i can then run the command like so `tfcmt --config tfcmt.yaml plan -- terraform plan`

**Comment by suzuki-shunsuke** [comment]
Oh, I found that we have to fix GitHub API v4 to support GitHub Enterprise.

**Comment by suzuki-shunsuke** [comment]
https://docs.github.com/en/enterprise-server@2.20/graphql/guides/forming-calls-with-graphql#the-graphql-endpoint
https://pkg.go.dev/github.com/shurcooL/githubv4#NewEnterpriseClient
https://pkg.go.dev/github.com/google/go-github/v44/github#NewEnterpriseClient

**Comment by suzuki-shunsuke** [comment]
https://github.com/suzuki-shunsuke/tfcmt/pull/304

**Comment by suzuki-shunsuke** [comment]
Released https://github.com/suzuki-shunsuke/tfcmt/releases/tag/v3.2.3

I don't use GitHub Enterprise, so I can't confirm if it works well for GitHub Enterprise.
I really appreciate if you confirm if it works well.

```console
tfcmt plan -patch -- terraform plan -no-color
```
