### ISSUE TITLE
Support for Terraform Planfiles

### ISSUE THREAD

**Issue by CubicNitrous** [suzuki-shunsuke/tfcmt#316]
Is there a way for this to run by passing it a terraform plan file or does it need to run terraform plan itself to work?

**Comment by suzuki-shunsuke** [comment]
You can use `terraform show` command instead of `terraform plan`.

https://www.terraform.io/cli/commands/show

```console
$ terraform plan -out tfplan.out
$ tfcmt plan -- terraform show tfplan.out
```
