### ISSUE TITLE
Plan Patch incorrectly editing comments

### ISSUE THREAD

**Issue by poiley** [suzuki-shunsuke/tfcmt#415]
I have a Github Actions workflow that performs `terraform plan` via `tfcmt` on multiple Terraform projects. Without the patch feature enabled, a comment is produced for each Terraform project each time `terraform plan` is run.

As it exists currently if the patch feature is enabled, the same comment is overwritten each time `terraform plan` run in the workflow regardless of the Terraform project.

The patch feature should make a comment for each `terraform plan` run, and then edit each separate comment rather than overwriting the same single comment each time.

**Comment by suzuki-shunsuke** [comment]
In case of multiple Terraform Projects, you should specify the `target` variable to distinguish projects.

https://suzuki-shunsuke.github.io/tfcmt/getting-started#monorepo-support-target-variable

e.g.

```console
$ tfcmt -var "target:foo" plan -- terraform plan
```

Then tfcmt would patch the correct comment.
