### ISSUE TITLE
patch doesn't respect embedded_var_names

### ISSUE THREAD

**Issue by wreulicke** [suzuki-shunsuke/tfcmt#447]
## Versions

tfcmt: v3.4.1

## How to reproduce

We have thew following config file.

```
embedded_var_names:
  - env
```

and then, run tfcmt.

```
$ tfcmt -var env:$env plan -patch -- terraform plan
```

## Expected Behavior

tfcmt patch the last comment that has same vars in comment metadata.

## Actual Behavior

tfcmt doesn't respect `Vars` except `target`.

## Note

* tfcmt can treat terraform workspace if patch respect embedded_vars

**Comment by suzuki-shunsuke** [comment]
Thank you for your report!

**Comment by wreulicke** [comment]
@suzuki-shunsuke 
I updated the description and added the note. tfcmt can treat terraform workspace if patch respect embedded_vars.
But, this is not current my requirement.

**Comment by suzuki-shunsuke** [comment]
Hmm. `embeddded_var_names` seems to work even if `-patch` is enabled.
https://github.com/suzuki-shunsuke/tfcmt/blob/d1a318da987eb3d3fccdac6539e4f22bf68c0e87/pkg/notifier/github/plan.go#L69-L105

Maybe you are misunderstanding the meaning of [embeddded_var_names](https://suzuki-shunsuke.github.io/tfcmt/embedded-metadata/#embedded_var_names).

tfcmt embedds the metada in comment like this.

```md
<!-- github-comment: {"Command":"plan","JobName":"terraform-plan","PRNumber":504,"Program":"tfcmt","SHA1":"***","Target":"github/foo","Vars":{},"WorkflowName":"test"} -->
```

`embeddded_var_names` is used to specify variables that are embedded in `Vars`.

**Comment by suzuki-shunsuke** [comment]
I guess you should specify `target` like this.

```console
$ tfcmt -var "target:$env" plan -patch -- terraform plan
```

**Comment by suzuki-shunsuke** [comment]
https://suzuki-shunsuke.github.io/tfcmt/embedded-metadata

The metadata is used to hide old comments with [github-comment](https://github.com/suzuki-shunsuke/github-comment#hide).
So if you patch comment, you don't have to specify `embeddded_var_names`.

**Comment by suzuki-shunsuke** [comment]
I found your tweet.

https://twitter.com/wreulicke/status/1570624528707100673

> tfcmt、embedded_var_namesを見てpatchしてくれたらなぁと思って
> issue立てたら、すぐにコメントの返信くれてbugのラベルがついた

Currently, tfcmt patches the comment with `target`, and doesn't support patching with `embedded_var_names`.
Do you have any reason that you would like to patch comments with not `target` but `embedded_var_names`?

**Comment by suzuki-shunsuke** [comment]
I haven't used Terraform Workspace, but I guess you should set the value such as `<workspace name>` or `<working directory path>/<workspace name>` (in case of Monorepo) to `target`.

**Comment by wreulicke** [comment]
@suzuki-shunsuke 
Sorry. I might misunderstand `target`.
I assumed that `target` is asscoiated with working directory.
We need to change working directory outside of tfcmt, right?

```
- steps:
  - run: tfcmt -var target:$ENV plan -patch -- terraform plan
    working_directory: $ENV
```

**Comment by wreulicke** [comment]
@suzuki-shunsuke 
Thanks for quickly response, and sorry for confusing you.
I read codes around handling plan command execution.
This issue is my misunderstanding.
https://github.com/suzuki-shunsuke/tfcmt/blob/a8eaf2c01fcf505e98dc4d30c99e839101f550f8/pkg/controller/plan.go#L36-L45

I close this issue.
